# application.properties

server.port=${PORT:5005}

# MongoDB Atlas Configuration
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://Mayank:Mayank123@auction.7q1qelr.mongodb.net/auction?retryWrites=true&w=majority&appName=Auction}
spring.data.mongodb.database=auction

# Jackson Naming Strategy for Snake Case
spring.jackson.property-naming-strategy=SNAKE_CASE
